name: EasyTransport
version: '2.5.2'
main: me.easytransport.EasyTransportPlugin
author: zZlag
api-version: '26.1'
depend: [Vault]
description: -Хуискриплеш! -Эй так нельзя! -Хуйзя
commands:
  etr:
    description: EasyTransport administration command
    usage: /etr
    aliases: [easytransport]
permissions:
  easytransport.admin:
    description: Allows management of EasyTransport
    default: op
